### ISSUE TITLE
Use Eslint for linting code , Prettier , and Use Babel transpiling 

### ISSUE THREAD

**Issue by MrSlimCoder** [alee-kolachi/ScrapeAPI#1]
Hi ali ! thanks for this api it helped me alot now get ready for my pull request on this . 
Can you please integrate eslint , prettier and babel in this project after that use ES6+ syntax .

**Comment by alee-kolachi** [comment]
Hello viveksharmaui, thanks for informing me about that. I am currently still working on those things, I uploaded those files to make sure I have secured its version.
